# Generated by Django 4.2.25 on 2025-11-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animatronics', '0002_category_manufacturer_animatronic_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animatronic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animatronics', to='animatronics.category'),
        ),
        migrations.AlterField(
            model_name='animatronic',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animatronics', to='animatronics.manufacturer'),
        ),
        migrations.AlterField(
            model_name='animatronic',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='animatronic',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
