# Generated by Django 4.2.25 on 2025-11-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animatronics', '0003_alter_animatronic_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animatronic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animatronics', to='animatronics.category'),
        ),
        migrations.AlterField(
            model_name='animatronic',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animatronics', to='animatronics.manufacturer'),
        ),
        migrations.AlterField(
            model_name='animatronic',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='animatronic',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
